### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [4mnesiac/4mnesiacYP.github.io#1]
Здравствуйте
Благодарю за проделанную работу.
К сожалению текущая реализация содержит ряд недостатков не позволяющих мне засчитать работу на данной итерации

Репозиторий
**Можно лучше** во всех ветках в рамках данного задания должна быть идентичная версия проекта.
Для это воспользуйтесь следующей схемой работы с репозиторием
1. Основная работа ведется в ветке develop
2. После окончания работы над веткой изменения сливаются в ветку master
3. Затем изменения из develop сливаются в ветку gh-pages
Необходимость данного подхода может быть не совсем понятна в рамках задания, однако это один из компонентов популярной методологии разработки git flow
Подробнее о ней можно узнать в следующих источниках:
https://habr.com/ru/post/106912/
https://bitworks.software/2019-03-12-gitflow-workflow.html

Регулярные выражения

**Можно лучше** (http|https)? эквивалентна https?
**Можно лучше** Квантификатор {1} можно не использовать. Он не играет никакой роли.

Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию:
some_user_name@gmail.com - имя пользователя может содержать несколько спецсимволов (главное чтобы они не были подряд)
some-extra-long-name@some.extra.long.domain.name - адрес может содержать произвольное количество поддоменов в доменном имени 

Номер телефона

**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

+7(925 900-90-90
+7925900-90-90
+792590090-90
+7-925-900-90-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

Адрес сайта:
**Нужно исправить** следующие корректные кейсы не проходят валидацию:
http://x.com:30 - доменное имя может состоять из одного символа

**Нужно исправить** следующие корректные кейсы не проходят валидацию:
http://google.ru:/path/to/deep - отсутствует номер порта после символа :
Если какой-то из моих комментариев требует большей детализации или разъяснения не стесняйтесь задавать вопросы.

**Comment by zlocate** [comment]
Добрый вечер. Остался один кейс требующий исправления:
**Нужно исправить** следующие корректные кейсы не проходят валидацию:
http://google.ru:/path/to/deep - отсутствует номер порта после символа :
Если какой-то из моих комментариев требует большей детализации или разъяснения не стесняйтесь задавать вопросы.

После внесения правок пожалуйста проверьте себя по чек-листу из поста ниже, там не все кейсы, однако основные присутствуют

**Comment by zlocate** [comment]
```
Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
http://ya.ru
https://www.ya.ru
http://google.ru:98/
http://x.com:30
http://google.ru/path/to/deep/
http://my-next-site.ru
http://8.8.8.8:8080
http://8.8.8.8:8080/page/to/deep#
http://some.test.stttttttttttttttest.yandex.ru

Негативные кейсы:
Проверку проходит следующий некорректный адреc сайта:
http://_.com
http://www.ya.
http://www (отсутствует доменная зона)
http://.ru (отсутствует доменное имя) 
http:something.ru (отсутствуют `//` после протокола) 
zzz://ya.ru (некорректный протокол. Допустимы только http\https)
http:\\google.ru
 httP://google.ru 
http://google.ru:/path/to/deep
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
http://something (отсутствует доменная зона)
http://1. (некорректный IP, точка на конце)
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
http://127. (некорректный IP, точка на конце)
http://127.0..  (некорректный IP, точка на конце)
http://127.0.0.. (некорректный IP, точка на конце) 
http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр) 
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
```
Надеюсь они будут вам полезны.

**Comment by 4mnesiac** [comment]
Спасибо за ревью. Некоторые пункты ввели в заблуждение, а именно 

> "Нужно исправить, следующие **корректные** кейсы не проходят валидацию:
http://google.ru:/path/to/deep - отсутствует номер порта после символа :"
И следом: 

> **Негативные кейсы:**
Проверку проходит следующий некорректный адреc сайта:
...
http://google.ru:/path/to/deep
...
Если я правильно понял, то данный кейс все таки некорректен, поэтому внес соответствующие правки и теперь он не валиден. Отправляю на ревью.
Еще раз спасибо, вы крутые!)

**Comment by zlocate** [comment]
Прошу прощения, опечатался, конечно же имел некорректные и проходят. 
Не там воткнул НЕ. Извините :(

**Comment by zlocate** [comment]
Такс, валидацию адресов сайта пока не смогли побороть до конца. Появились следующие проблемы:
**Можно лучше**
http://8.8.8.8:8080/pa###ge/to/d##eep/################ - можно воткнуть произвольное число # в url и он будет считать валидным

**Нужно исправить**: 
http://100.100.100.00220901/pa###ge/to/d##eep/################ - некорректный IP-адрес проходит валидацию.

З.Ы Спасибо за столь лестную оценку моему ревью. Очень приятно :)

**Comment by 4mnesiac** [comment]
Загрузить проект на ревью через Практикум не могу из-за статуса "Задание проверяется код-ревьюером", поэтому уведомляю здесь, что внес соответствующие ~~костыли~~ правки :)

**Comment by zlocate** [comment]
@4mnesiac вижу. Проверяю

**Comment by zlocate** [comment]
Отличная работа. Кейсы отмеченные выше исправлены. Работа принята
